### ISSUE TITLE
Problem with margin on FAB

### ISSUE THREAD

**Issue by SilkSama** [gowong/material-sheet-fab#1]
Thanks for your job.

There is a problem when I set a margin to the FAB.
I try to use your component with a fullscreen sheet and if I have a margin on the FAB the sheet is shifted. (regarding to the fab margins)

**Comment by gowong** [comment]
Hi,

This is because whenever opening the sheet, the sheet's position is automatically aligned with the FAB. I may add an attr in the future to disable this behavior, but for now you can add negative margins to your sheet as a workaround:

```xml
<android.support.design.widget.FloatingActionButton
    android:id="@+id/overview_fab"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_marginRight="16dp"
    android:layout_marginBottom="16dp" />

<android.support.v7.widget.CardView
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_marginRight="-16dp"
    android:layout_marginBottom="-16dp">
```
