### ISSUE TITLE
fab hide and show

### ISSUE THREAD

**Issue by TheLoyalCruel** [gowong/material-sheet-fab#10]
in your sample app
how to hide and show fab when recyclerView scrolls up and down?
thanks

**Comment by gowong** [comment]
That's out of the scope for this library. 
You can however use a FAB library that already supports that functionality, such as this one https://github.com/makovkastar/FloatingActionButton

**Comment by TheLoyalCruel** [comment]
thanks
another question is that.. I have this library:
    compile 'com.github.ozodrukh:CircularReveal:1.1.1@aar'
in my project and there is conflict... It has dexDebug error! how to solve this?

**Comment by gowong** [comment]
I think you can just remove that line since this library already includes CircularReveal for you.
Let me know if that doesn't work.

**Comment by TheLoyalCruel** [comment]
thanks... it works :)
