### ISSUE TITLE
disable touch outside the sheet

### ISSUE THREAD

**Issue by TheLoyalCruel** [gowong/material-sheet-fab#11]
when I touch outside the sheet, it hides the sheet!
how to hidesheet(); just forexample by a sheetItem click?

**Comment by gowong** [comment]
Are you looking to hide the sheet when clicking an item in the sheet? If so, the sample app already does this so you can take a look at that.

**Comment by TheLoyalCruel** [comment]
ok I see that... my problem is something else!
how to cancel hidesheet when clicking outside the sheet? I mean I want the fab sheet stay when I click somewhere else in touchscreen...

**Comment by gowong** [comment]
After creating the MaterialSheetFab:

```java
new MaterialSheetFab<>(fab, sheetView, overlay, sheetColor, fabColor);
```

You can override the touch listener on the overlay:

```java
overlay.setOnTouchListener(new View.OnTouchListener() {
			@Override
			public boolean onTouch(View view, MotionEvent motionEvent) {
				return false;
			}
		});
```

Let me know how that goes!
