### ISSUE TITLE
Not working on S3

### ISSUE THREAD

**Issue by Lesilva** [gowong/material-sheet-fab#14]
On S3, when click on FAB, the sheet show at the top corner and just a small part visible. When click somewhere else on screen trying to cancel the sheet, FAB button stays hidden. I'm using the FAB implementation from your sample app.

**Comment by Lesilva** [comment]
Works fine on Nexus 6

**Comment by gowong** [comment]
Could you post a screenshot of what you're seeing? Also, what version of Android is it running?

**Comment by Lesilva** [comment]
![screen shot 2015-10-07 at 10 22 45 am](https://cloud.githubusercontent.com/assets/3347243/10340315/838c9ce0-6cdd-11e5-843c-bc64baec1442.png)
![screen shot 2015-10-07 at 10 23 26 am](https://cloud.githubusercontent.com/assets/3347243/10340318/8672e694-6cdd-11e5-9752-a4a1079fad3b.png)

**Comment by Lesilva** [comment]
First one is top left, second one should show the other FAB. All happens on pre-lolipop samsung device

**Comment by gowong** [comment]
Is the sample app working fine on your device?

**Comment by gowong** [comment]
No response, feel free to reopen.
