### ISSUE TITLE
how to delete notes

### ISSUE THREAD

**Issue by roshu10** [gowong/material-sheet-fab#18]
Is it possible to implement on note click listener ?

I want to delete note on some event (either long press or onClick event)(its not demonstrated in sample app too)

Is that possible ??

**Comment by gowong** [comment]
Hi,
The sample app isn't meant to be a functioning notes app. It is just to demonstrate a possible use case for this library. But yes, it should be pretty straightforward to add an onClickListener to each note view and then do the deletion there.

**Comment by roshu10** [comment]
Thanks for the reply.

I just started with Android programming.

Can you Plz explain where to add on click listener for this?
