### ISSUE TITLE
APK signing -> Error: Expected resource of type anim [ResourceType]

### ISSUE THREAD

**Issue by Tibolte** [gowong/material-sheet-fab#20]
Based on the sample app, I created my own Fab implementing AnimatedFab, and when generating a signed apk, Gradle returns me this error:

Error:(126) Error: Expected resource of type anim [ResourceType]

This is happening when providing the interpolator:

private Interpolator getInterpolator() {
       return AnimationUtils.loadInterpolator(getContext(), R.interpolator.msf_interpolator);
}

I fixed it temporarily by using new AccelerateDecelerateInterpolator() because I had to release my app. But this shouldn't be hard to fix :)

**Comment by gowong** [comment]
Did you include the `msf_interpolator` file in your project when you saw the error?

**Comment by Tibolte** [comment]
No I was trying to get the one from the library.

**Comment by gowong** [comment]
Right, did your project have material-sheet-fab/material-sheet-fab/src/main/res/values/refs.xml 
and  material-sheet-fab/material-sheet-fab/src/main/res/values-v21/refs.xml?

**Comment by gowong** [comment]
It looks like this is a false Lint error - you'll have to manually suppress it or you can replace `R.interpolator.msf_interpolator` with `android.R.interpolator.accelerate_decelerate`.
The source for [`AnimationUtils.loadInterpolator`](https://github.com/android/platform_frameworks_base/blob/7eaccbfbc25b772659536c096f6341927c38c470/core/java/android/view/animation/AnimationUtils.java#L271) expects an `@InterpolatorRes` so Lint is incorrectly reporting an error here.

**Comment by mecoFarid** [comment]
Add this code to your build.gradle (Module: app)
```
android {
 lintOptions {
    disable "ResourceType"
  }
}

```
