### ISSUE TITLE
Fab is located in a wrong spot on < 5.0 devices

### ISSUE THREAD

**Issue by hatpick** [gowong/material-sheet-fab#25]
I have followed your sample code and created my own view, but the fab is located in a wrong place. With the "show layout bounds" enabled in debugging mode, I can see that the fab has some padding on < 5.0 devices. Any idea what might causing the issue?

<img width="289" alt="screen shot 2016-03-14 at 5 47 32 pm" src="https://cloud.githubusercontent.com/assets/1483492/13765675/b6fcc74a-ea18-11e5-8d51-70433b38a369.png">
<img width="258" alt="screen shot 2016-03-14 at 5 48 01 pm" src="https://cloud.githubusercontent.com/assets/1483492/13765678/bbc654ee-ea18-11e5-851c-e7c6097bab12.png">

**Comment by gowong** [comment]
Can you post a screenshot?

**Comment by hatpick** [comment]
I've attached the screenshots, you can see that there is some padding around the Fab.

**Comment by gowong** [comment]
Ah I see, this is an issue in the Android Design Support library where the spacing isn't consistent across Android versions. The example app actually accounts for this. If you look at the styles - there are separate padding values based on the platform.
