### ISSUE TITLE
Readme Fab sample

### ISSUE THREAD

**Issue by apex39** [gowong/material-sheet-fab#30]
Sample class of Fab shown in README should contain all three defaulf constructors:

```
public Fab(Context context) {
        super(context);
    }

public Fab(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

public Fab(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);
    }

```

IDE yells that class has no default constructor but a programmer who has no idea how widgets are implemented can run into XML inflating error when implementing only one constructor.

**Comment by gowong** [comment]
Putting this in the readme is unnecessary since it's obvious the constructors are needed and the IDE helps autocomplete them.
