### ISSUE TITLE
Fab is not shown after sheet is closed

### ISSUE THREAD

**Issue by TadejZupancic** [gowong/material-sheet-fab#32]
I want to leave the sheet open after the device rotation, so if the sheet was open, then I manually call showSheet(). Sheet is shown as expected, but when I close it by pressing back key, the sheet is closed, but the fab does not appear. If I don't call showSheet(), the fab shows and works as usual.

Is this a bug or do I have to call something else for the fab to show after closing the sheet?

**Comment by FrantisekSpurny** [comment]
I have the same issue. Call "hideSheet()" hides not only the sheet, but also the FAB.

**Comment by gowong** [comment]
Try calling both `showFab()` and `showSheet()`

**Comment by FrantisekSpurny** [comment]
I was trying to do that but with no effect.

But i worked my way around. The problem was i occuring when i tried to hide fab sheet at the same moment as i was displaying dialog. Solution was to hide sheet and when its hidden start dialog.

**Comment by TadejZupancic** [comment]
showFab() does not help. I found out it works if I call it like this:
```
new Handler().post(new Runnable() {
    @Override
     public void run() {
         materialSheetFab.showSheet();
     }
});
```
But calling only materialSheetFab.showSheet() does not show the fab after the sheet is closed.
