### ISSUE TITLE
No resources found

### ISSUE THREAD

**Issue by prashanthd** [gowong/material-sheet-fab#34]
I tried using 1.2.1 and 1.0.4 version. I got below error in both versions.

`Error:(2174, 21) No resource found that matches the given name: attr 'cardBackgroundColor'.
Error:(2175, 21) No resource found that matches the given name: attr 'cardCornerRadius'.
Error:(2173, 21) No resource found that matches the given name: attr 'contentPadding'.
Error:(2193, 21) No resource found that matches the given name: attr 'cardBackgroundColor'.
Error:(2194, 21) No resource found that matches the given name: attr 'cardElevation'.
Error:(2195, 21) No resource found that matches the given name: attr 'cardMaxElevation'.
Error:(2196, 21) No resource found that matches the given name: attr 'contentPadding'.
Error:(2174, 21) No resource found that matches the given name: attr 'cardBackgroundColor'.
Error:(2175, 21) No resource found that matches the given name: attr 'cardCornerRadius'.
Error:(2173, 21) No resource found that matches the given name: attr 'contentPadding'.
Error:(2193, 21) No resource found that matches the given name: attr 'cardBackgroundColor'.
Error:(2194, 21) No resource found that matches the given name: attr 'cardElevation'.
Error:(2195, 21) No resource found that matches the given name: attr 'cardMaxElevation'.
Error:(2196, 21) No resource found that matches the given name: attr 'contentPadding'.`

**Comment by gowong** [comment]
Did you download the support library using the SDK manager?

**Comment by prashanthd** [comment]
I just added gradle dependency compile 'com.gordonwong:material-sheet-fab:1.2.1' .. Do I need to do anything more?

**Comment by gowong** [comment]
Does it compile if you remove `material-sheet-fab` from your dependencies?
The error looks like support lib is not installed. https://developer.android.com/topic/libraries/support-library/setup.html#download
