### ISSUE TITLE
Issue: can't import

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [gowong/material-sheet-fab#36]
After trying to import and updating all things, I still get this error:

> Gradle 'material-sheet-fab' project refresh failed
> Error:No service of type Factory<LoggingManagerInternal> available in ProjectScopeServices.

How come?

**Comment by gowong** [comment]
The library hasn't been actively developed for some time so some of the plugins are outdated. Try updating 
[`material-sheet-fab/build.gradle`](material-sheet-fab/build.gradle).
A quick google search gave me this https://code.google.com/p/android/issues/detail?id=219692

**Comment by AndroidDeveloperLB** [comment]
Can you please update it?

**Comment by gowong** [comment]
Are you trying to modify the library (by forking it) or are you importing into your project with `compile 'com.gordonwong:material-sheet-fab:1.2.1'`? The latter should still work.

**Comment by AndroidDeveloperLB** [comment]
Just clone, import, build and run

**Comment by gowong** [comment]
Okay, you'll need to update the gradle file then. My comments above should have all the info you need.

**Comment by AndroidDeveloperLB** [comment]
As I wrote, I tried to update everything. It didn't help.
Please fix the project to work on new IDE version and all..

**Comment by github-ogawa-PC1** [comment]
有り難うございます。
