### ISSUE TITLE
java.lang.NullPointerException: isSheetVisible()

### ISSUE THREAD

**Issue by PeterPhyo** [gowong/material-sheet-fab#37]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.gordonwong.materialsheetfab.MaterialSheetFab.isSheetVisible()' on a null object reference

```
    @Override
    public void onBackPressed() {
        if (materialSheetFab.isSheetVisible()) {
            materialSheetFab.hideSheet();
        } else {
            super.onBackPressed();
        }
    }
```

Sorry, I found a problem. 😄

**Comment by gowong** [comment]
Did you initialize `materialSheetFab`? The error is saying that it's null when you press the back button.
