### ISSUE TITLE
How can I call AlertDialog.Builder after pressing Fab button?

### ISSUE THREAD

**Issue by felipheggaliza** [gowong/material-sheet-fab#40]
Hi, congratulations for the good job!

I have a question though...

I would like to use Android built-in AlertDialog, and generally I set the title and message using AlertDialog.Builder in the Activity code.

How can I do it in a way the user press the Fab button, and it gets animated to show alert dialog instead of a CardView, as shown in the examples?

**Comment by gowong** [comment]
This isn't supported. You'll need to fork the library and implement your own animations to work with alert dialogs.
