### ISSUE TITLE
CardView doesn't have a margin on < 5.0 Lollipop

### ISSUE THREAD

**Issue by XxPixX** [gowong/material-sheet-fab#7]
Hi, There isn't any margin on devices without lollipop in the CardView.
I read in a previous issue that the margin is 16dp and I can see that on my nexus 6 running 5.1.1 but on a samsung galaxy s running 4.4.4 then there is no margin.

**Comment by masoodfallah** [comment]
oh why???

**Comment by gowong** [comment]
Are you referring to the sample app or your own app?
The library doesn't add margins to the CardView so you'll need to do that with your own styling.

**Comment by gowong** [comment]
No response. Feel free to reopen.
