### ISSUE TITLE
CardView radius style is not applied

### ISSUE THREAD

**Issue by ticofab** [gowong/material-sheet-fab#8]
Hi, and thanks for this library. Unfortunately I am not able to style the cardview in the material sheet. For instance, attributes such as `cardCornerRadius` or `cardBackgroundColor` don't have any effect, nor in my app nor trying to modify the sample app. Trying to achieve this via code doesn't work either. Have you noticed the same behaviour?

**Comment by gowong** [comment]
Hi, are you able to style a cardview that isn't  being used by the library? The fab doesn't override any of the sheet's existing styles except for the background colors, which you pass in the fab's constructor.

**Comment by gowong** [comment]
No response. Feel free to reopen.

**Comment by ticofab** [comment]
Hey @gowong , sorry I have had little time in the past few days. Indeed you are right -- I can't style cardviews in general. The issue doesn't depend on your library. If you have any further clue why my card views are not styleable, that'd be welcome :) Thanks again for this wonderful library.

**Comment by gowong** [comment]
I think I had issues setting the radius on the cardviews in the past, but I can try again later today. Is it only the radius style that isn't working for you?

**Comment by ticofab** [comment]
No - other attributes such as `card_view:contentPadding` are also not working.

**Comment by gowong** [comment]
Okay, I found the issue that's preventing the `cardCornerRadius` from being applied on Android 5.0+, but it should already be working on older version of Android. Can you confirm that's the case?
I should be able to push a fix tomorrow.

**Comment by ticofab** [comment]
You are right -- attributes such as `cardCornerRadius` work fine on older version. Specifically, I tried it on 4.4.4 (KitKat).

**Comment by gowong** [comment]
Fixed in v1.0.5

**Comment by ticofab** [comment]
Thanks for fixing this!
